// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package stderr represents the interface "wasi:cli/stderr@0.2.0".
package stderr

import (
	"github.com/ydnar/wasm-tools-go/wasi/io/streams"
)

// GetStderr represents function "wasi:cli/stderr@0.2.0#get-stderr".
//
//	get-stderr: func() -> own<output-stream>
//
//go:nosplit
func GetStderr() streams.OutputStream {
	return wasmimportGetStderr()
}

//go:wasmimport wasi:cli/stderr@0.2.0 get-stderr
//go:noescape
func wasmimportGetStderr() streams.OutputStream
