// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package stdin represents the interface "wasi:cli/stdin@0.2.0".
package stdin

import (
	"github.com/ydnar/wasm-tools-go/wasi/io/streams"
)

// GetStdin represents function "wasi:cli/stdin@0.2.0#get-stdin".
//
//	get-stdin: func() -> own<input-stream>
//
//go:nosplit
func GetStdin() streams.InputStream {
	return wasmimportGetStdin()
}

//go:wasmimport wasi:cli/stdin@0.2.0 get-stdin
//go:noescape
func wasmimportGetStdin() streams.InputStream
