// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package terminalstderr represents the interface "wasi:cli/terminal-stderr@0.2.0".
//
// An interface providing an optional `terminal-output` for stderr as a
// link-time authority.
package terminalstderr

import (
	"github.com/ydnar/wasm-tools-go/cm"
	terminaloutput "github.com/ydnar/wasm-tools-go/wasi/cli/terminal-output"
)

// GetTerminalStderr represents function "wasi:cli/terminal-stderr@0.2.0#get-terminal-stderr".
//
// If stderr is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
//
//	get-terminal-stderr: func() -> option<own<terminal-output>>
//
//go:nosplit
func GetTerminalStderr() cm.Option[terminaloutput.TerminalOutput] {
	var result cm.Option[terminaloutput.TerminalOutput]
	getTerminalStderr(&result)
	return result
}

//go:wasmimport wasi:cli/terminal-stderr@0.2.0 get-terminal-stderr
//go:noescape
func getTerminalStderr(result *cm.Option[terminaloutput.TerminalOutput])
