// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package instancenetwork represents the interface "wasi:sockets/instance-network@0.2.0".
//
// This interface provides a value-export of the default network handle..
package instancenetwork

import (
	"github.com/ydnar/wasm-tools-go/wasi/sockets/network"
)

// InstanceNetwork represents function "wasi:sockets/instance-network@0.2.0#instance-network".
//
// Get a handle to the default network.
//
//	instance-network: func() -> own<network>
//
//go:nosplit
func InstanceNetwork() network.Network {
	return wasmimportInstanceNetwork()
}

//go:wasmimport wasi:sockets/instance-network@0.2.0 instance-network
//go:noescape
func wasmimportInstanceNetwork() network.Network
