// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package stdout represents the interface "wasi:cli/stdout@0.2.0".
package stdout

import (
	"github.com/ydnar/wasm-tools-go/wasi/io/streams"
)

// GetStdout represents function "wasi:cli/stdout@0.2.0#get-stdout".
//
//	get-stdout: func() -> own<output-stream>
//
//go:nosplit
func GetStdout() streams.OutputStream {
	return getStdout()
}

//go:wasmimport wasi:cli/stdout@0.2.0 get-stdout
//go:noescape
func getStdout() streams.OutputStream
